services:
    jupyter:
        build: .
        runtime: nvidia
        user: root
        ports:
          - "8888:8888"
        volumes:
          - ${PWD}/projects:/home/jovyan/projects
          - /home/raynor/datasets/:/home/jovyan/datasets
        working_dir: /home/jovyan/projects
        environment: 
            - NB_UID=1008 
            - NB_GID=1008 
            - CHOWN_HOME=yes
            - CHOWN_HOME_OPTS=-R
            - NVIDIA_VISIBLE_DEVICES=2,3
        