hydra:
  run:
    dir: outputs/${run.name}/${run.tags}/${hydra.job.override_dirname}
  sweep:    
    dir: multirun/${run.name}/
    subdir: ${hydra.job.override_dirname}
  job:    
    config:
      override_dirname:
        exclude_keys:          
          - run.name
          - run.tags

run:
  name: 'stickmanf'
  tags: '${now:%Y-%m-%d_%H-%M-%S}'

model:
  checkpoint_path: ''

bijection: 
  type: 'vanilla'
  params:
    conv_widths: [16,32]
    num_conv_layers_per_scale: 4
    mlp_width: 392
    num_mlp_layers: 2
  
data:
  image_path: "../../datasets/stickman/g"
  ext: 'png'
  image_size: 32
  num_channels: 1
  train_split: 0.1
  num_bits: 5

train:
  sigma_output: 0.1
  num_epochs: 100
  batch_size: 64
  num_warmup_epochs: 1
  num_sample_epochs: 0.5 # Fractional epochs for sampling because one epoch is quite long 
  num_save_epochs: 1
  num_samples: 9

optim:
  init_lr: 0.0001