defaults:
  - data: generate

train:
  batch_size: 64
  lr: 0.01
  epochs: 1000
  print_epoch: 10
  train_split: 1
  alpha: 0

PRNGSeed: 0


model:
  features: [256, 1]

run:
  type: Real

hydra:
  run:
    dir: ./outputs/${run.type}/${now:%Y-%m-%d}/${now:%H-%M-%S}